# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts to run before build
before_build:
  - nuget restore -DisableParallelProcessing

build:
  project: Kentor.AuthServices.sln
  verbosity: Minimal

test_script:
  - .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:vstest.console.exe -targetargs:".\Kentor.AuthServices.Tests\bin\Debug\Kentor.AuthServices.Tests.dll /logger:Appveyor" -returntargetcode -filter:"+[Kentor*]* -[Kentor.AuthServices.Test*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder to avoid repeated downloads for nuget restore
